[package]
name = "AOC2021"
version = "0.1.0"
authors = ["Andr√© von Landenberg <andre@vonlandenberg.de>"]
edition = "2021"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"